version: "3"

services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18
    tty: true
    volumes:
      - "../:/workspace"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres?schema=public

  db:
    image: postgres:15-alpine
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
